"""empty message

Revision ID: c696e8a3db58
Revises: fd00dc5b4d59
Create Date: 2023-10-17 16:06:04.639828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c696e8a3db58'
down_revision = 'fd00dc5b4d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('favorite_people_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_people_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_email'], ['email'])
        batch_op.create_foreign_key(None, 'people', ['people_name'], ['name'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('people_id')

    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_email', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('favorite_planets_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_planets_planets_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planets_name'], ['name'])
        batch_op.create_foreign_key(None, 'user', ['user_email'], ['email'])
        batch_op.drop_column('planets_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_planets_planets_id_fkey', 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key('favorite_planets_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_email')
        batch_op.drop_column('planets_name')

    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_people_people_id_fkey', 'people', ['people_id'], ['id'])
        batch_op.create_foreign_key('favorite_people_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_email')
        batch_op.drop_column('people_name')

    # ### end Alembic commands ###
